FIND_LIBRARY(UV_LIBRARY NAMES uv PATHS libuv)

INCLUDE_DIRECTORIES(libuv/include)
INCLUDE_DIRECTORIES(http-parser)

SET(CMAKE_CXX_FLAGS_DEBUG "-g -pg -O0")

HHVM_EXTENSION(uv uv.cpp http-parser/http_parser.c)
HHVM_SYSTEMLIB(uv uv.php)

TARGET_LINK_LIBRARIES(uv ${UV_LIBRARY})
