FIND_LIBRARY(UV_LIBRARY NAMES uv PATHS libuv)

INCLUDE_DIRECTORIES(libuv/include)

SET(CMAKE_CXX_FLAGS_DEBUG "-g -pg -O0")

HHVM_EXTENSION(uv uv.cpp)
HHVM_SYSTEMLIB(uv uv.php)

TARGET_LINK_LIBRARIES(uv ${UV_LIBRARY})
